### ISSUE TITLE
Not executing transform function

### ISSUE THREAD

**Issue by wesleylancel** [Metrakit/gulp-fontastic#1]
This looks cool, but I tried it using a version of the example code and it doesn't seem to execute the transform function.

**Comment by Metrakit** [comment]
Hi @wesleylancel , thanks for the feedback. It works well for me. I will try that as sound as possible  and give you help.

**Comment by Metrakit** [comment]
@wesleylancel the plugin works perfectly, I have tried it again yesterdy with the new release that I have published. Can you give me more informations about this issue ?

**Comment by rubencustodio** [comment]
Also, not working for me at all. Please update.

**Comment by Metrakit** [comment]
What is displaying on your CLI? I use that for all my projects I havent problems. I need some informations for help you. Which Gulp version are you using ?

**Comment by Metrakit** [comment]
It's the same? the transform function isn't executed ?

**Comment by daedlock** [comment]
make sure you run it inside a `pipe()`.

**Comment by moacir-selinger** [comment]
Hello, this tool is very good. When I use the content in your documentation, I have no error, but it also does not work.

I'm required to add an execution to a .pipe (), which returns on the console "(node: 2783) DeprecationWarning: Calling an asynchronous function with no callback is deprecated.", But this works.

Could you clarify if I'm wrong?

**Comment by x-hta** [comment]
I have the same error(The transform fn is not called). Any idea how to get this fixed?

**Comment by Metrakit** [comment]
Fixed thanks to @esdras
